# Generated by Django 2.1.5 on 2019-01-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='titutlo',
            new_name='titulo',
        ),
    ]
