# Generated by Django 2.1.5 on 2019-01-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_pergunta_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
