# Generated by Django 2.1.5 on 2019-01-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_questionario_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.Pergunta'),
        ),
    ]
